

/* TOYS */
export const GET_MESS_OWNERS = "GET_MESS_OWNERS"
export const GET_MESS_OWNERS_SUCCESS = "GET_MESS_OWNERS_SUCCESS"
export const GET_MESS_OWNERS_FAIL = "GET_MESS_OWNERS_FAIL"

/**
 * add TOY
 */
export const ADD_NEW_MESS_OWNER = "ADD_NEW_MESS_OWNER"
export const ADD_MESS_OWNER_SUCCESS = "ADD_MESS_OWNER_SUCCESS"
export const ADD_MESS_OWNER_FAIL = "ADD_MESS_OWNER_FAIL"

/**
 * Edit TOY
 */
export const UPDATE_MESS_OWNER = "UPDATE_MESS_OWNER"
export const UPDATE_MESS_OWNER_SUCCESS = "UPDATE_MESS_OWNER_SUCCESS"
export const UPDATE_MESS_OWNER_FAIL = "UPDATE_MESS_OWNER_FAIL"

/**
 * Delete TOY
 */
export const DELETE_MESS_OWNER = "DELETE_MESS_OWNER"
export const DELETE_MESS_OWNER_SUCCESS = "DELETE_MESS_OWNER_SUCCESS"
export const DELETE_MESS_OWNER_FAIL = "DELETE_MESS_OWNER_FAIL"